### ISSUE TITLE
smoothnet & deciwatch, which is better?

### ISSUE THREAD

**Issue by ykk648** [cure-lab/DeciWatch#1]
or we can use both?

**Comment by ailingzengzzz** [comment]
Hi @ykk648,

They have different focuses.
For SmoothNet, it is used for smoothing jitters to get a smooth curve or pose sequence, which generalizes well across different 2D,3D, or 6D modalities (share weights across spatial dimensions). It needs to input the **whole** detected poses. 

For DeciWatch, it focuses on high efficiency with lower mean Flops and faster inference speeds via skipping and estimating highly sparse input frames, e.g., estimating one frame in every ten frames. It inputs **sparse** detected poses. Because DeciWatch utilizes the continuity of human motions, it can also output a smooth pose sequence after RecoverNet.

Therefore, you can choose which method to use depending on your needs.

**Comment by ykk648** [comment]
@ailingzengzzz Thanks for your response, I have tested DeciWatch under mmhuman3d framework , the results looks similar to `slerp` for me, it can replace filter to some extent , SmoothNet looks like a CNN-version filter with motion supervision, I'm willing to test it after next update of mmhuman3d.

**Comment by ailingzengzzz** [comment]
@ykk648  The learning-based methods will show their effectiveness when the inputs are quite noisy. If the inputs look good, traditional filters or interpolation manners will also work well.
