### ISSUE TITLE
How's the smooth effect on root joint transitions?

### ISSUE THREAD

**Issue by lucasjinreal** [cure-lab/DeciWatch#11]
Hi, does there any root joints transition optimization comparation result?

**Comment by ailingzengzzz** [comment]
Hi @jinfagang,

All our results are from root-zero position errors, which are the commonly used settings for 3d pose and SMPL estimation. For the smoothing root joint transitions, since the global positions of the root joint are larger than other relative joints, you can simply normalize the root joint into [-1, 1] and put it into SmoothNet.
