### ISSUE TITLE
SmoothNet vs. Transformer as the denoise and recover net

### ISSUE THREAD

**Issue by xiexh20** [cure-lab/DeciWatch#12]
Dear authors,

Thanks for your amazing work and releasing the code!
In your other work SmoothNet, you showed that temporal-only network is superior to a transformer. However, here you use a vanilla transformer module as the denoise and recover net. In theory, these two networks can also be simply replaced by two SmoothNets. I am wondering have you done these experiments before? And what is your insight into these? 
Thanks!

Best,
Xianghui

**Comment by ailingzengzzz** [comment]
Hi @xiexh20,

This is an interesting question! The two networks can be used to remove jitters and outputs smooth poses. 

For the Acceleration errors to measure the jitter issue, SmoothNet tends to have lower errors since it is a temporal-only model that can focus on reducing jitters along the temporal axis. Moreover, it is spatial-agnostic and can be used for any spatial modalities with good generalization ability.

I have tried putting **a SmoothNet** to replace both DenoiseNet and RecoverNet. It works with better MPJPEs and Accels than the input single-frame methods and traditional interpolation methods. However, DeciWatch will be better than SmoothNet in the average position errors. The reasons might be that given highly sparse poses, the temporal-only SmoothNet only relies on the temporal consistency to denoise and recover the whole pose sequence, which is hard. The transformer here can aggregate **spatial-temporal information together** to get a lower denoise error. From the limited information, utilizing both spatial and temporal information will gain more than only temporal information. In addition, for the AIST++ dataset, DeciWatch can refine a lot compared with SmoothNet. In our ablation study, we also change the Transformer block into MLPs, showing a slightly inferior performance.

**Comment by xiexh20** [comment]
thanks for your detailed explanation!

*for the AIST++ dataset, DeciWatch can refine a lot compared with SmoothNet.*
Is it because the AIST++ dataset is more challenging hence the pose estimation results are more noisy? 

If so, is it in general that the temporal-only method would suffer more from large input noise (bias error) while transformer  works better as it also utilizes the spatial information?

**Comment by ailingzengzzz** [comment]
The main reason is we directly use the pretrained model (e.g., SPIN) on previous many datasets to test it on the AIST++ dataset, making the estimated poses noisy. It needs more spatial-temporal correlations to correct the poses rather than only temporal consistency. 

Actually, it's difficult to claim transformers work better since they will be related to the data and some designs of the models. In our experiments, linear layers across the temporal axis model the temporal consistency better than the self-attention scheme (please check out our other paper if you are interested: https://arxiv.org/pdf/2205.13504.pdf). But in the vanilla transformer, they utilize spatial features together, which is convenient here for the simple baseline. You can try to further modify the spatial-temporal feature extraction for better denoising and recovery.

**Comment by xiexh20** [comment]
thanks for your explaination!
