### ISSUE TITLE
Use my own dataset to generate negative optimization

### ISSUE THREAD

**Issue by haofeng0705** [cure-lab/DeciWatch#17]
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/30925823/197087671-565becea-6a21-4d02-bbab-6879831e68e5.png">
Im using my own processed npz files to test Deciwatch , but why the output error is bigger than input error?

**Comment by juxuan27** [comment]
Hi, @Elliot-hao ! Thank you for your focus and apologize for the late reply.
I see you're using your own processed data for testing. For custom data, you may need to adjust model parameters for better performance depending on your data scale and distribution. Moreover, the sampling interval would have a strong influence on the output accuracy. With a bigger interval, the inference speed will be faster, however, the accuracy will rise and then drop. So, it is reasonable for an output error bigger than the input error because we need to sacrifice a little accuracy for faster inference speed. Moreover, uniform sampling is just a baseline method, DeciWatch still has a big room for improvement.
