### ISSUE TITLE
3D custom data format

### ISSUE THREAD

**Issue by CloudedLeopard17** [cure-lab/DeciWatch#6]
Hi,
I am trying to run inference on 3D detection data, I have the body coordinates of people. What preprocessing do I need to do for inference? I normalised the data wrt the hip centre. I tried to visualise prepared data and the person was upside down, I am little confused. 
![download](https://user-images.githubusercontent.com/33505589/180813116-7886a667-d767-432a-9a56-d5522764f636.png)

**Comment by juxuan27** [comment]
Hi @CloudedLeopard17 , thank you for your focus.
Do you mean that you want to inference your own dataset? If so, you can follow the instruction [here](https://github.com/cure-lab/DeciWatch/blob/main/doc/data.md) to make your own dataset. If you only want to inference the prepared data, just follow the instruction [here](https://github.com/cure-lab/DeciWatch/blob/main/doc/evaluate.md).
For the upside-down human, we didn't deliberately place the human body like that. It is probably because the estimator's output is original upside down, and we simply copy it into our data. DeciWatch is not sensitive to the person's orientation, so if you need to generate your own dataset, you do not need to turn it to specific orientation.

**Comment by CloudedLeopard17** [comment]
Hi @juxuan27  thanks for the reply, I tried to do inference on my custom data but I am getting empty `predicted_pos, denoised_pos` outputs in visualize.py. I am passing joints_3d inputs normalized by the hip centre. Is the joints_3d input correct?

**Comment by CloudedLeopard17** [comment]
@juxuan27 I was able to run inference on my custom data. Thanks for the great work.
